version: '3.7'

networks:
  backend-net:
    driver: bridge
  traefik-net:
    external: true

services:

  minio:
    image: quay.io/minio/minio
    container_name: minio
    volumes:
      - /var/share/minio:/data
      - ./minio.env:/etc/config.env
    environment:
      - "MINIO_CONFIG_ENV_FILE=/etc/config.env"
    command: server --console-address ":9401"
    restart: unless-stopped
    networks:
      - backend-net
      - traefik-net
    ports:
      - 9400:9000
      - 9401:9401
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.minio.rule=Host(`minio.dieren.gerull.nl`)"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9400"
      - "traefik.http.routers.admin.rule=Host(`minio-console.dieren.gerull.nl`)"
      - "traefik.http.routers.admin.service=admin"
      - "traefik.http.services.admin.loadbalancer.server.port=9401"
      - "org.label-schema.group=storage"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
