version: '3.7'

networks:
  backend-net:
    driver: bridge
  traefik-net:
    external: true

services:

  postgresql:
    image: postgres:16.1-alpine3.18
    container_name: postgresql
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
      # - ./minio.env:/etc/config.env
    environment:
      POSTGRES_PASSWORD: P@55w0rd
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - backend-net
      - traefik-net
    ports:
      - 5432:5432
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.minio.rule=Host(`minio.dieren.gerull.nl`)"
    #   - "traefik.http.services.minio.loadbalancer.server.port=9401"
    #   - "traefik.docker.network=traefik-net"
#      - "traefik.http.routers.minio-console.rule=Host(`minio-console.dieren.gerull.nl`)"
#      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      # - "org.label-schema.group=storage"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgresql-exporter
    environment:
      DATA_SOURCE_NAME>: "postgresql://postgres:P@55w0rd@postgresql:5432/postgres?sslmode=disable"
    ports:
      - 9187:9187
    networks:
      - backend-net
    depends_on:
      - postgresql

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgresql:5432/vehicle_management -user=postgres -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    networks:
      - backend-net
    depends_on:
      - postgresql